language: c

before_install:
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository -y ppa:git-core/ppa > /dev/null 2>&1
  - sudo apt-get update
  - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
  - sudo apt-get install git-lfs 
  - sudo git lfs install
  
addons:
  apt:
    packages:
      - git
      - libasound2:i386
      - libcairo2:i386
      - libz1:i386
      - libbz2-1.0:i386
      - libssl1.0.0:i386
      - libfreetype6:i386
      - software-properties-common

install: 
  - ./scripts/download.sh
  - ./scripts/install-packages.sh
  - ./scripts/upload.sh
  
script:
  - echo " "
